project:
  type: book
  output-dir: docs

book:
  title: "Data Structures and Algorithms (BST 234) Notes"
  author: "Christian Testa"
  chapters:
    - index.qmd
    - week1/week1.qmd
    - week2/week2.qmd
    - week3/week3.qmd
    - week4/week4.qmd
    - week5/week5.qmd
    - week6/week6.qmd
    - week7/week7.qmd


bibliography: references.bib
reference-location: margin
citation-location: margin

format:
  html:
    theme: style.scss
    number-sections: false
  pdf:
    documentclass: scrreport

filters:
  - pseudocode